name: isolate_utils
description: IsolateUtils provides a way to launch dart isolate in Flutter (iOS and Android).
version: 2.0.0
homepage: https://github.com/thongdn-it/isolate_utils
repository: https://github.com/thongdn-it/isolate_utils

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
