name: isolate_utils
description: IsolateUtils provides a way to launch dart isolate in Flutter (iOS and Android).
version: 1.0.0+1
homepage: https://github.com/thongdn-it/isolate_utils
repository: https://github.com/thongdn-it/isolate_utils

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
